#pragma once


#ifndef CLASSES_H
#define CLASSES_H
#include <cstddef>

class C_BaseEntity
{
public:

};

class CBasePlayer
{
public:
	static constexpr std::ptrdiff_t AnimTimeMustBeFirst = 0x0;
	static constexpr std::ptrdiff_t m_flAnimTime = 0xa0;
	static constexpr std::ptrdiff_t m_flSimulationTime = 0xb0;
	static constexpr std::ptrdiff_t m_ubInterpolationFrame = 0xc0;
	static constexpr std::ptrdiff_t m_vecOrigin = 0x438;
	static constexpr std::ptrdiff_t m_angRotation = 0x444;
	static constexpr std::ptrdiff_t m_nModelIndex = 0xd4;
	static constexpr std::ptrdiff_t m_fEffects = 0xc4;
	static constexpr std::ptrdiff_t m_nRenderMode = 0xc2;
	static constexpr std::ptrdiff_t m_nRenderFX = 0x8c;
	static constexpr std::ptrdiff_t m_clrRender = 0x90;
	static constexpr std::ptrdiff_t m_iTeamNum = 0xe4;
	static constexpr std::ptrdiff_t m_CollisionGroup = 0x454;
	static constexpr std::ptrdiff_t m_flElasticity = 0x300;
	static constexpr std::ptrdiff_t m_flShadowCastDistance = 0x304;
	static constexpr std::ptrdiff_t m_hOwnerEntity = 0x744;
	static constexpr std::ptrdiff_t m_hEffectEntity = 0x748;
	static constexpr std::ptrdiff_t moveparent = 0x21c;
	static constexpr std::ptrdiff_t m_iParentAttachment = 0x1fe;
	static constexpr std::ptrdiff_t movetype = 0x0;
	static constexpr std::ptrdiff_t movecollide = 0x0;
	static constexpr std::ptrdiff_t m_Collision = 0x230;
	static constexpr std::ptrdiff_t m_vecMinsPreScaled = 0x240;
	static constexpr std::ptrdiff_t m_vecMaxsPreScaled = 0x24c;
	static constexpr std::ptrdiff_t m_vecMins = 0x258;
	static constexpr std::ptrdiff_t m_vecMaxs = 0x264;
	static constexpr std::ptrdiff_t m_nSolidType = 0x279;
	static constexpr std::ptrdiff_t m_usSolidFlags = 0x274;
	static constexpr std::ptrdiff_t m_nSurroundType = 0x278;
	static constexpr std::ptrdiff_t m_triggerBloat = 0x27a;
	static constexpr std::ptrdiff_t m_vecSpecifiedSurroundingMinsPreScaled = 0x27c;
	static constexpr std::ptrdiff_t m_vecSpecifiedSurroundingMaxsPreScaled = 0x288;
	static constexpr std::ptrdiff_t m_vecSpecifiedSurroundingMins = 0x294;
	static constexpr std::ptrdiff_t m_vecSpecifiedSurroundingMaxs = 0x2a0;
	static constexpr std::ptrdiff_t m_iTextureFrameIndex = 0x738;
	static constexpr std::ptrdiff_t predictable_id = 0x0;
	static constexpr std::ptrdiff_t m_PredictableID = 0xe8;
	static constexpr std::ptrdiff_t m_bIsPlayerSimulated = 0x734;
	static constexpr std::ptrdiff_t m_bSimulatedEveryTick = 0x735;
	static constexpr std::ptrdiff_t m_bAnimatedEveryTick = 0x736;
	static constexpr std::ptrdiff_t m_bAlternateSorting = 0x737;
	static constexpr std::ptrdiff_t m_takedamage = 0xd6;
	static constexpr std::ptrdiff_t m_RealClassName = 0x780;
	static constexpr std::ptrdiff_t m_OverrideMaterial = 0x784;
	static constexpr std::ptrdiff_t m_OverrideSubMaterials = 0x0;
	static constexpr std::ptrdiff_t m_iHealth = 0xd8;
	static constexpr std::ptrdiff_t m_iMaxHealth = 0xdc;
	static constexpr std::ptrdiff_t m_spawnflags = 0x92c;
	static constexpr std::ptrdiff_t m_iGModFlags = 0x930;
	static constexpr std::ptrdiff_t m_bOnFire = 0x77a;
	static constexpr std::ptrdiff_t m_CreationTime = 0x77c;
	static constexpr std::ptrdiff_t m_vecVelocity_x = 0x150;
	static constexpr std::ptrdiff_t m_vecVelocity_y = 0x154;
	static constexpr std::ptrdiff_t m_vecVelocity_z = 0x158;
	static constexpr std::ptrdiff_t m_GMOD_DataTable = 0x1638;
	static constexpr std::ptrdiff_t m_GMOD_bool = 0x998;
	static constexpr std::ptrdiff_t m_GMOD_float = 0x9b8;
	static constexpr std::ptrdiff_t m_GMOD_int = 0xa38;
	static constexpr std::ptrdiff_t m_GMOD_Vector = 0xab8;
	static constexpr std::ptrdiff_t m_GMOD_QAngle = 0xc38;
	static constexpr std::ptrdiff_t m_GMOD_EHANDLE = 0xdb8;
	static constexpr std::ptrdiff_t m_GMOD_String0 = 0xe38;
	static constexpr std::ptrdiff_t m_GMOD_String1 = 0x1038;
	static constexpr std::ptrdiff_t m_GMOD_String2 = 0x1238;
	static constexpr std::ptrdiff_t m_GMOD_String3 = 0x1438;
	static constexpr std::ptrdiff_t m_iCreationID = 0x16a4;
	static constexpr std::ptrdiff_t m_iMapCreatedID = 0x16a8;
	static constexpr std::ptrdiff_t m_nSequence = 0x19ec;
	static constexpr std::ptrdiff_t m_nForceBone = 0x1714;
	static constexpr std::ptrdiff_t m_vecForce = 0x1708;
	static constexpr std::ptrdiff_t m_nSkin = 0x16c0;
	static constexpr std::ptrdiff_t m_nBody = 0x16c4;
	static constexpr std::ptrdiff_t m_nHitboxSet = 0x16c8;
	static constexpr std::ptrdiff_t m_flModelScale = 0x1800;
	static constexpr std::ptrdiff_t m_flModelWidthScale = 0x1800;
	static constexpr std::ptrdiff_t m_flPoseParameter = 0x1804;
	static constexpr std::ptrdiff_t m_flPlaybackRate = 0x16fc;
	static constexpr std::ptrdiff_t m_flEncodedController = 0x1950;
	static constexpr std::ptrdiff_t m_bClientSideAnimation = 0x19e9;
	static constexpr std::ptrdiff_t m_bClientSideFrameReset = 0x17a6;
	static constexpr std::ptrdiff_t m_nNewSequenceParity = 0x19c0;
	static constexpr std::ptrdiff_t m_nResetEventsParity = 0x19c4;
	static constexpr std::ptrdiff_t m_nMuzzleFlashParity = 0x1ac8;
	static constexpr std::ptrdiff_t m_hLightingOrigin = 0x1ac0;
	static constexpr std::ptrdiff_t m_hLightingOriginRelative = 0x1ac4;
	static constexpr std::ptrdiff_t serveranimdata = 0x0;
	static constexpr std::ptrdiff_t m_flCycle = 0x19f0;
	static constexpr std::ptrdiff_t m_fadeMinDist = 0x1790;
	static constexpr std::ptrdiff_t m_fadeMaxDist = 0x1794;
	static constexpr std::ptrdiff_t m_flFadeScale = 0x1798;
	static constexpr std::ptrdiff_t m_pBoneManipulator = 0x1b74;
	static constexpr std::ptrdiff_t m_pFlexManipulator = 0x1b7c;
	static constexpr std::ptrdiff_t m_OverrideViewTarget = 0x1ae8;
	static constexpr std::ptrdiff_t overlay_vars = 0x0;
	static constexpr std::ptrdiff_t m_AnimOverlay = 0x0;
	static constexpr std::ptrdiff_t lengthproxy = 0x0;
	static constexpr std::ptrdiff_t lengthprop15 = 0x0;
	static constexpr std::ptrdiff_t m_flexWeight = 0x1cb0;
	static constexpr std::ptrdiff_t m_blinktoggle = 0x1e80;
	static constexpr std::ptrdiff_t m_viewtarget = 0x1c50;
	static constexpr std::ptrdiff_t m_vecViewOffset_x = 0x144;
	static constexpr std::ptrdiff_t m_vecViewOffset_y = 0x148;
	static constexpr std::ptrdiff_t m_vecViewOffset_z = 0x14c;
	static constexpr std::ptrdiff_t m_vecLean = 0x2040;
	static constexpr std::ptrdiff_t m_vecShift = 0x20a0;
	static constexpr std::ptrdiff_t bcc_localdata = 0x0;
	static constexpr std::ptrdiff_t m_flNextAttack = 0x2108;
	static constexpr std::ptrdiff_t m_hActiveWeapon = 0x2914;
	static constexpr std::ptrdiff_t m_bloodColor = 0x2110;
	static constexpr std::ptrdiff_t pl = 0x2bf8;
	static constexpr std::ptrdiff_t deadflag = 0x2c00;
	static constexpr std::ptrdiff_t m_hVehicle = 0x2c90;
	static constexpr std::ptrdiff_t m_hUseEntity = 0x2c98;
	static constexpr std::ptrdiff_t m_lifeState = 0xd7;
	static constexpr std::ptrdiff_t m_hColorCorrectionCtrl = 0x34e8;
	static constexpr std::ptrdiff_t m_flMaxspeed = 0x2c9c;
	static constexpr std::ptrdiff_t m_fFlags = 0x450;
	static constexpr std::ptrdiff_t m_iObserverMode = 0x2c64;
	static constexpr std::ptrdiff_t m_hObserverTarget = 0x2c68;
	static constexpr std::ptrdiff_t m_iFOV = 0x2c10;
	static constexpr std::ptrdiff_t m_iFOVStart = 0x2c14;
	static constexpr std::ptrdiff_t m_flFOVTime = 0x2c18;
	static constexpr std::ptrdiff_t m_iDefaultFOV = 0x2c20;
	static constexpr std::ptrdiff_t m_hZoomOwner = 0x2c24;
	static constexpr std::ptrdiff_t m_hViewModel = 0x2d68;
	static constexpr std::ptrdiff_t m_bUseWeaponsInVehicle = 0x2d33;
	static constexpr std::ptrdiff_t localdata = 0x0;
	static constexpr std::ptrdiff_t m_Local = 0x2980;
	static constexpr std::ptrdiff_t m_chAreaBits = 0x2988;
	static constexpr std::ptrdiff_t m_chAreaPortalBits = 0x29a8;
	static constexpr std::ptrdiff_t m_iHideHUD = 0x29c0;
	static constexpr std::ptrdiff_t m_flFOVRate = 0x29c4;
	static constexpr std::ptrdiff_t m_bDucked = 0x29c8;
	static constexpr std::ptrdiff_t m_bDucking = 0x29c9;
	static constexpr std::ptrdiff_t m_bInDuckJump = 0x29ca;
	static constexpr std::ptrdiff_t m_flDucktime = 0x29cc;
	static constexpr std::ptrdiff_t m_flDuckJumpTime = 0x29d0;
	static constexpr std::ptrdiff_t m_flJumpTime = 0x29d4;
	static constexpr std::ptrdiff_t m_flFallVelocity = 0x29dc;
	static constexpr std::ptrdiff_t m_vecPunchAngle = 0x29f0;
	static constexpr std::ptrdiff_t m_vecPunchAngleVel = 0x2a50;
	static constexpr std::ptrdiff_t m_bDrawViewmodel = 0x2ab0;
	static constexpr std::ptrdiff_t m_bWearingSuit = 0x2ab1;
	static constexpr std::ptrdiff_t m_bPoisoned = 0x2ab2;
	static constexpr std::ptrdiff_t m_flStepSize = 0x2ab4;
	static constexpr std::ptrdiff_t m_bAllowAutoMovement = 0x2ab3;
	static constexpr std::ptrdiff_t m_fSprintSpeed = 0x2bd4;
	static constexpr std::ptrdiff_t m_fWalkSpeed = 0x2bd8;
	static constexpr std::ptrdiff_t m_fSlowWalkSpeed = 0x2bdc;
	static constexpr std::ptrdiff_t m_fLadderSpeed = 0x2be0;
	static constexpr std::ptrdiff_t m_fCrouchedWalkSpeed = 0x2be4;
	static constexpr std::ptrdiff_t m_fDuckSpeed = 0x2be8;
	static constexpr std::ptrdiff_t m_fUnDuckSpeed = 0x2bec;
	static constexpr std::ptrdiff_t m_bDuckToggled = 0x2bd1;
	static constexpr std::ptrdiff_t m_flFriction = 0x318;
	static constexpr std::ptrdiff_t m_iAmmo = 0x2114;
	static constexpr std::ptrdiff_t m_nTickBase = 0x2d20;
	static constexpr std::ptrdiff_t m_nNextThinkTick = 0xcc;
	static constexpr std::ptrdiff_t m_hLastWeapon = 0x2d40;
	static constexpr std::ptrdiff_t m_hGroundEntity = 0x30c;
	static constexpr std::ptrdiff_t m_vecBaseVelocity = 0x1d8;
	static constexpr std::ptrdiff_t m_hConstraintEntity = 0x2c48;
	static constexpr std::ptrdiff_t m_vecConstraintCenter = 0x2c4c;
	static constexpr std::ptrdiff_t m_flConstraintRadius = 0x2c58;
	static constexpr std::ptrdiff_t m_flConstraintWidth = 0x2c5c;
	static constexpr std::ptrdiff_t m_flConstraintSpeedFactor = 0x2c60;
	static constexpr std::ptrdiff_t m_flDeathTime = 0x2c8c;
	static constexpr std::ptrdiff_t m_flLaggedMovementValue = 0x3310;
	static constexpr std::ptrdiff_t m_hTonemapController = 0x2bf0;
	static constexpr std::ptrdiff_t m_hViewEntity = 0x350c;
	static constexpr std::ptrdiff_t m_bDisableWorldClicking = 0x34fd;
};

#endif